stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: infoubicatecl/${CICD_GIT_REPO_NAME}/rancher-demo:latest
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
notification: {}
